- .gitignore
Added to git ignore:
+test/SampleApplication/.vscode/launchReactNative.js
+test/SampleApplication/.vscode/settings.json
+test/SampleApplication/tsconfig.json
+test/SampleApplication/.vscode/typings/
> Added Sample Application auto-generated files to git ignore

- src/extension/tsconfigHelper.ts
> Don't change allowJs if already set

- .gitignore
Updated .gitignore to reflect SampleApplication new path
> Updated .gitignore to reflect SampleApplication new path

- src/common/commandExecutor.ts
- src/common/extensionMessaging.ts
- src/common/nestedError.ts
- src/common/node/childProcess.ts
- src/common/node/request.ts
- src/debugger/ios/deviceDeployer.ts
- src/debugger/ios/deviceRunner.ts
- src/typings/q/Q.d.ts
@dlebu @joshuaskelton @meenakb @MSLaguana @MShamiltonia @guillaumejenkins
Do you think that forcing all rejections to be an error would improve our code or make it worse?
> Changed all the rejections to use an Error parameter (no typings change)

- package.json
- src/common/reactNativeProjectHelper.ts
- src/typings/semver/semver.d.ts
Now we use semver to verify the current version of the react-native package
> Now we use semver to verify the current version of the react-native package

- src/debugger/appWorker.ts
Adding handler for $disconnect, and now we (re)create the sandbox each time we receive a prepareJSRuntime (The previous code assumed that the socket connection was dropped before a reload, which is not always true).
> Now we create a Sandbox on prepareJSRuntime and destroy it on $disconnect

- src/extension/commandPaletteHandler.ts
- src/extension/extensionServer.ts
- src/extension/packagerStatusIndicator.ts
- src/extension/rn-extension.ts
> Adding a status bar indicator to indicate the Packager status

- src/common/hostPlatform.ts
Now it works on Windows and OSX too :)
> Small bug-fix to the platforms code

- package.json
- src/debugger/ios/deviceRunner.ts
- src/test/common/commandExecutor.test.ts
- src/test/debugger/ios/deviceRunner.test.ts
- src/typings/semver/semver.d.ts
- src/typings/should/should.d.ts
- Added tests for CommandExecutor.
- Ported DeviceRunner tests from Taco.
> Added CommandExecutor and Device Runner tests

- src/common/hostPlatform.ts
- src/common/log/logHelper.ts
- tslint.json
> Adding no-switch-case-fall-through rule to tslint.

- src/common/log/logHelper.ts
Created a new log level for internal logging. The default level is none.
> Now we have a different log level for the internal logging

- src/test/debugger/ios/deviceRunner.test.ts
tslint is working as expected :+1:
> Fixing minor tslint issue.

- src/common/ios/iOSDebugModeManager.ts
- src/debugger/appWorker.ts
- src/debugger/launcher.ts
- src/extension/intellisenseHelper.ts
Fixing spelling mistakes.
Fixes: #131
> Fix spelling errors

- src/debugger/android/androidPlatform.ts
> Fix broken code, and formatted it properly

- tools/checkCopyright.js
We can use this to debug errors on our build system
> Now we print a stack trace on copyright errors

- src/common/commandExecutor.ts
- src/common/log/log.ts
- src/common/log/loggers.ts
- src/extension/outputChannelLogger.ts
Data stream buffer should be output without trailing newlines
> Fixes #139

- src/test/debugger/sourceMap.test.ts
Increasing test coverage for source map helper.
> Adding More SourceMap Tests

- gulpfile.js
- tools/gulp-extras.js
Added a new gulp task: `gulp package`
> Added package gulp task.

- src/common/android/deviceHelper.ts
- src/common/extensionMessaging.ts
- src/common/hostPlatform.ts
- src/common/node/childProcess.ts
- src/common/node/fileSystem.ts
- src/common/node/package.ts
- src/common/outputVerifier.ts
- src/common/reactNative.ts
- src/debugger/android/androidPlatform.ts
Decoupled code so it's easier to test it. Some unrelated minor fixes.
> Decoupled code so it's easier to test it. Some unrelated minor fixes.

- src/common/commandExecutor.ts
- src/common/ios/iOSDebugModeManager.ts
- src/common/ios/simulatorPlist.ts
- src/common/node/childProcess.ts
- src/common/packager.ts
- src/common/reactNative.ts
- src/debugger/ios/deviceRunner.ts
- src/debugger/ios/iOSPlatform.ts
- src/extension/android/logCatMonitor.ts
- src/extension/commandPaletteHandler.ts
- src/extension/extensionServer.ts
Fixes https://github.com/Microsoft/vscode-react-native/issues/191
Fixes bug where packager incorrectly says it finished just after it was started.
> Fix bugs in the command palette run commands

- package.json
This adds the launch parameters to package.json. Maybe someone can add descriptions - I'm note sure about the meaning of each.
This fixes #223
> Fix launch parameters

- ReactTypings/react-native/react-native.d.ts
- src/debugger/scriptImporter.ts
fixes a typo and remove a console.log from production code
> fix typo and remove console.log (overriden -> overridden)

- tools/gulp-extras.js
> Simple spelling fix

- README.md
Fixes #296 by improving documentation.
> Adding documentation for changing packager port

- package.json
Changing to 0.2.0 after addition of exponent functionality.
> Updating package.json ready for release

- package.json
> Update package.json ready for release

- src/debugger/appWorker.ts
This PR fixes `Maximum stack size exceeded` error when debugging app, built with react-native@0.37
See #340 for reference
> Add hook to intercept regenerator's lazy getter

- src/extension/intellisenseHelper.ts
- src/extension/tsconfigHelper.ts
Since version 1.7.2 VSCode automatically installs typings for dependencies mentioned in package.json so we don't need to install typings at extension initialization. Previous behavior is still retained for previous VSCode versions though.
This also changes type of project manifest to `jsconfig.json` since ATA works only for javascript projects.
> Do not install typings in VSCode >= 1.7.2

- CHANGELOG.md
> Minor typo fix for CHANGELOG.md

- README.md
Update the known issues section to reflect the fix of [#5850](https://github.com/facebook/react-native/issues/5850).
> Update know issues after bugfix

- src/common/packager.ts
This PR fixes launching VSCode as an editor when tapping on stack frame.
It doesn't work with the latest react native (actually with  0.38, 0.39, 0.40 versions) due to [the bug](https://github.com/facebook/react-native/commit/f49093f39710173620fead6230d62cc670570210) with launching VSCode editor, which will be fixed in 0.41.
Please also note that the current implementation has also been broken since RN 0.38 due to changed parsing algorithm, i.e. instead of `node <path>/atom` `REACT_EDITOR` variable reads as `node`.
There's also been [the bug](https://github.com/facebook/react-native/blob/master/local-cli/server/util/launchEditor.js#L83) with incorrect path parsing on windows, leading to path to our `atom` stub being parsed as `'d:react-nativevscode-react-nativescriptsatom'`.
Related …
> Open source file in VSCode when tapping on stack frame

- CHANGELOG.md
- package.json
Update CHANGELOG
Bump version in package.json
> Prepare 0.3.2 release

- README.md
Added information in docs about how flowtype should be configured as discussed in #85
> Add flowtype to docs

- src/debugger/nodeDebugWrapper.ts
Support for VSCode@1.14.0
#471
> Fix for incorrect builder restarts

- src/common/exponent/xdlInterface.ts
- src/common/node/request.ts
- src/common/packager.ts
- src/debugger/scriptImporter.ts
- src/extension/commandPaletteHandler.ts
- src/extension/extensionServer.ts
- src/extension/rn-extension.ts
- src/test/common/packager.test.ts
- Install expo deps correctly
- Correctly handle running packager instance
> Fix bugs in Expo support logic

- src/common/ios/iOSDebugModeManager.ts
- src/common/ios/plistBuddy.ts
- src/debugger/ios/iOSPlatform.ts
- src/extension/commandPaletteHandler.ts
> Fix automatic enable of JS debugging on iOS sims

- README.md
- package.json
- src/common/android/androidPlatform.ts
- src/common/extensionMessaging.ts
- src/common/launchArgs.ts
- src/common/reactNative.ts
- src/common/remoteExtension.ts
- src/debugger/nodeDebugWrapper.ts
- src/extension/commandPaletteHandler.ts
- src/extension/extensionServer.ts
- src/extension/rn-extension.ts
- src/extension/settingsHelper.ts
> App running options

- README.md
- package.json
- src/common/android/androidPlatform.ts
- src/common/extensionMessaging.ts
- src/common/ios/iOSPlatform.ts
- src/common/launchArgs.ts
- src/common/reactNative.ts
- src/common/remoteExtension.ts
- src/debugger/nodeDebugWrapper.ts
- src/extension/commandPaletteHandler.ts
- src/extension/extensionServer.ts
- src/extension/settingsHelper.ts
- src/test/debugger/android/androidPlatform.test.ts
- src/test/resources/reactNative022.ts
> Run option for specific native source folder

- src/common/android/androidPlatform.ts
- src/common/generalMobilePlatform.ts
- src/common/ios/iOSPlatform.ts
> Fix run-android out of the box

- doc/customization.md
- src/common/android/adb.ts
- src/common/android/androidPlatform.ts
- src/common/generalMobilePlatform.ts
- src/common/ios/iOSPlatform.ts
- src/extension/commandPaletteHandler.ts
- src/extension/rn-extension.ts
- test/debugger/ios/iOSPlatform.test.ts
- test/resources/simulators/adbSimulator.ts
> Custom packager port support

- src/debugger/nodeDebugWrapper.ts
- src/extension/extensionServer.ts
> Show error message from Extension.launch

- README.md
- doc/tasks.md
> Added info about tasks in README

- .vscode/launch.json
- package.json
- src/common/packagerStatus.ts
- src/debugger/appWorker.ts
- src/debugger/forkedAppWorker.ts
- src/debugger/nodeDebugWrapper.ts
- src/debugger/scriptImporter.ts
- src/debugger/sourceMap.ts
- test/debugger/appWorker.test.ts
- test/debugger/sourceMap.test.ts
> Implement attach to remote packager

- CHANGELOG.md
- README.md
- doc/tasks.md
- package.json
> Prepare 0.4.3 release

- CHANGELOG.md
- package.json
- src/extension/extensionServer.ts
> Fixed issue with Run iOS on device

- src/extension/extensionServer.ts
> Bugfix runArguments options

- src/extension/rn-extension.ts
> Delete settings change warning message

- src/extension/rn-extension.ts
Fixes launch and debug for RN projects with RN root in subfolder
> Fix RN project in sub-folder debug

- src/debugger/appWorker.ts
- src/debugger/scriptImporter.ts
> Added support react-native version gte 0.50

- src/common/packager.ts
- src/extension/commandPaletteHandler.ts
- src/extension/settingsHelper.ts
- test/extension/android/androidPlatform.test.ts
- test/extension/ios/iOSPlatform.test.ts
Fixes command pallete commands for different project root.
Reported in issue #561
> Fix command pallete commands for different project root

- src/common/packager.ts
> Fix bug with Expo packagerOpts

- package.json
- src/extension/android/androidPlatform.ts
- src/extension/commandPaletteHandler.ts
- src/extension/generalMobilePlatform.ts
- src/extension/ios/iOSPlatform.ts
- src/extension/launchArgs.ts
- src/extension/settingsHelper.ts
> Set Environment Variable

- npm-shrinkwrap.json
- package.json
- src/extension/generalMobilePlatform.ts
> Merge env vars

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> Fix bug with .envFile

- src/common/packager.ts
> Fix skip prewarm message

- src/debugger/nodeDebugWrapper.ts
> Respect launch.json port setting for attach to packager

- package.json
> skipFiles option definition

- doc/debugging.md
fixes https://github.com/Microsoft/vscode-react-native/issues/617#issuecomment-364824746
> [docs] use runArguments to specify device/schema and etc

- src/extension/appcenter/lib/codepush-node-sdk/dist/react-native/react-native-utils.js
- src/extension/appcenter/lib/codepush-node-sdk/src/react-native/react-native-utils.ts
Fixes issue with not finding index{os}.js file #637
> Fix entry path

- src/extension/appcenter/codepush/codepush-sdk/src/update-contents/code-signing/hash-utils.ts
- src/extension/appcenter/codepush/codepush-sdk/src/update-contents/code-signing/sign.ts
- src/extension/appcenter/codepush/codepush-sdk/src/update-contents/zip.ts
This function can throw errors.
> Fixed isDirectory() function.

- src/common/outputVerifier.ts
- src/extension/android/androidPlatform.ts
- src/extension/ios/iOSPlatform.ts
- src/extension/windows/windowsPlatform.ts
- test/extension/android/androidPlatform.test.ts
This PR complements error message for "not all success patterns were matched" error.
> Update error message for "not all success patterns were matched" error

- src/common/telemetry.ts
- src/common/telemetryReporters.ts
- src/debugger/nodeDebugWrapper.ts
- src/extension/rn-extension.ts
e.g.
`undefined/launch` -> `react-native-tools/launch`
> Fix telemetry extension ID

- src/common/error/errorStrings.ts
> Fixed "IOSDeployNotFound" error message

- src/debugger/nodeDebugWrapper.ts
This PR add check whether directory in which debug has been launched is a React Native project. It prevents debugger to stuck with the such message in output window:
```
{ Error: connect ENOENT /tmp/vscode-reactnative-3ac6a0299f88064cac596ab8d8463ced9844a1d6805afefc4da3790e722144e7.sock
at Object.exports._errnoException (util.js:1050:11)
at exports._exceptionWithHostPort (util.js:1073:20)
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'connect',
address: '/tmp/vscode-reactnative-3ac6a0299f88064cac596ab8d8463ced9844a1d6805afefc4da3790e722144e7.sock' }{ Error: connect ENOENT /tmp/vscode-reactnative-3ac6a0299f88064cac596ab8d8463ced9844a1d6805afefc4da3790e722144e7.sock
at Object.exports._errnoException (util.js:1050:11)
at …
```
> Add check for project root in debugger

- src/extension/commandPaletteHandler.ts
> The correct project root for Run iOS commands

- package.json
- src/common/error/errorStrings.ts
- src/common/error/internalErrorCode.ts
- src/common/packager.ts
- src/extension/commandPaletteHandler.ts
- src/extension/exponent/exponentPlatform.ts
- src/extension/extensionServer.ts
- src/extension/generalMobilePlatform.ts
- src/extension/packagerStatusIndicator.ts
- src/extension/rn-extension.ts
Resolve #713
\+ refactoring for exponent packager
> Packager refactoring. Action buttons for status bar

- doc/debugging.md
- package.json
- src/common/targetPlatformHelper.ts
- src/extension/platformResolver.ts
- src/extension/windows/windowsPlatform.ts
- src/extension/windows/wpfPlatform.ts
> Added debugger for WPF platform

- src/common/reactNativeProjectHelper.ts
> Update list of versions with broken metro bundler

- src/common/packager.ts
> Remove outdated patch for CRNA

- src/common/packager.ts
- src/extension/exponent/exponentHelper.ts
> Fixed error while stop expo packager

- src/debugger/nodeDebugWrapper.ts
- src/extension/commandPaletteHandler.ts
- src/extension/rn-extension.ts
> Added some logging for debug

- src/debugger/nodeDebugWrapper.ts
> Disconnect debugger from debuggee process(hardstop)

- src/common/packager.ts
- test/extension/packager.test.ts
> Do not use --root packager arg for RN@0.57

- test/debugger/appWorker.test.ts
> Fix appWorket test on windows

- package.json
- package.nls.it.json
- package.nls.json
Since I was having troubles with the last PR i made a clean one.
> Externalized commands titles and added categories.

- npm-shrinkwrap.json
- src/extension/exponent/exponentPlatform.ts
- src/extension/qrCodeContentProvider.ts
- src/extension/rn-extension.ts
#827 Migrating to new WebView API
> Migrate from vscode.previewHtml command to new VS Code WebView API

- package-lock.json
- package.json
Fix vulnerability described in this [issue](https://github.com/dominictarr/event-stream/issues/116)
> Fix for event stream package vulnerability

- src/extension/extensionServer.ts
- src/extension/generalMobilePlatform.ts
> Add more strings for localization from extension folder

- src/common/error/errorStrings.ts
- src/common/error/internalErrorCode.ts
- src/debugger/appWorker.ts
- src/debugger/forkedAppWorker.ts
#820
Example of how this errors would look
> Refactor debugger errors, add error codes for them

- package-lock.json
- package.json
PR updates isparta version to resolve security vulnerabilities.
> Update isparta version

- src/debugger/scriptImporter.ts
> Fix debugger url for haul projects

- doc/expo.md
- src/extension/exponent/exponentHelper.ts
- test/extension/exponent/exponentHelper.test.ts
>  Update expo debugging instructions for pure React Native apps, add warning

- release/AdditionalAttributions.txt
> Add additional attributions information

- gulpfile.js
> Refactor gulpfile.js to move from Transifex to Microsoft Localization platform

- package-lock.json
- package.json
> Bump vscode version to 1.1.27

- package-lock.json
- package.json
> Bump debug-core deps

- test/smoke/azure-pipelines.yml
- test/smoke/src/helpers/setupEnvironmentHelper.ts
- test/smoke/src/main.ts
- test/smoke/src/spectron/application.ts
> [Smoke tests] Add React Native VSIX installation stage,  add Android emulator execution stage,  add android emulator termination flow

- .gitignore
- .vscodeignore
- test/smoke/azure-pipelines.yml
- test/smoke/package.json
- test/smoke/src/areas/debug/debug.ts
- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/helpers/appiumHelper.ts
- test/smoke/src/helpers/expoAppHelper.ts
- test/smoke/src/helpers/setupEnvironmentHelper.ts
- test/smoke/src/helpers/smokeTestsConstants.ts
- test/smoke/src/main.ts
- test/smoke/src/spectron/application.ts
- test/smoke/yarn.lock
> [Smoke Tests] CI - Add CI configuration for Debug Android smoke test

- test/smoke/.gitignore
- test/smoke/package.json
- test/smoke/yarn.lock
[AB#476](https://dev.azure.com/vscode-webdiag-extensions/web/wi.aspx?pcguid=3cf843ad-ff14-4241-b13b-8f3d749f94db&id=476)
> [Smoke tests] Add mocha-junit-reporter for the tests

- gulpfile.js
- package-lock.json
- package.json
> Update vscode-nls-dev to the latest version for compatibility with MLCP

- package-lock.json
AB#478
https://www.npmjs.com/advisories/755
> Bump handlebars version to avoid vulnerability

- release/AdditionalAttributions.txt
- src/extension/ios/iOSDebugModeManager.ts
- src/extension/ios/iOSPlatform.ts
- src/extension/ios/plistBuddy.ts
- src/extension/ios/simulatorPlist.ts
- test/extension/ios/plistBuddy.test.ts
- test/extension/ios/simulatorPlist.test.ts
> Fix ios debugging on RN 0.59

- .vscode/tasks.json
- test/smoke/src/areas/debug/debug.ts
- test/smoke/src/main.ts
- test/smoke/src/spectron/application.ts
- test/smoke/src/spectron/client.ts
PR fixes tslint problems and prevents build-smoke-tests task output window to take focus.
> [Smoke tests] Fix minor issues

- package-lock.json
- package.json
> Fix js-yaml vulnerability

- doc/expo.md
- src/extension/exponent/exponentHelper.ts
[AB#367](https://dev.azure.com/vscode-webdiag-extensions/web/wi.aspx?pcguid=3cf843ad-ff14-4241-b13b-8f3d749f94db&id=367)
> Update docs section for running pure React Native apps via Expo

- test/smoke/src/helpers/appiumHelper.ts
Move call React Native DevMenu logic in a separate function
> [Smoke tests] Refactor call React Native DevMenu logic

- test/smoke/.gitignore
- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/main.ts
Change tests results xmls ignore list
> Fix test suites names for better readability

- test/smoke/src/helpers/appiumHelper.ts
- test/smoke/src/helpers/setupEnvironmentHelper.ts
- test/smoke/src/main.ts
[AB#13](https://dev.azure.com/vscode-webdiag-extensions/web/wi.aspx?pcguid=3cf843ad-ff14-4241-b13b-8f3d749f94db&id=13)
> [Smoke tests] Fix paths for Linux

- CHANGELOG.md
- package-lock.json
- package.json
- release/ThirdPartyNotices.txt
> Prepare for 0.9.2

- test/smoke/package.json
- test/smoke/src/main.ts
- test/smoke/src/spectron/application.ts
- test/smoke/yarn.lock
* Bump Electron version
* Improved logging
* Minor fixes
[AB#477](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/477)
> [Smoke tests] Add collecting logs from the extension

- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/debugIos.test.ts
- test/smoke/src/helpers/androidEmulatorHelper.ts
- test/smoke/src/helpers/appiumHelper.ts
[AB#598](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/598)
> [Smoke Tests] Refactor android helper to consolidate it with ios ones

- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/debugIos.test.ts
- test/smoke/src/helpers/androidEmulatorHelper.ts
- test/smoke/src/helpers/appiumHelper.ts
- test/smoke/src/helpers/iosSimulatorHelper.ts
- test/smoke/src/helpers/setupEnvironmentHelper.ts
- test/smoke/src/helpers/utilities.ts
- test/smoke/src/helpers/vsCodeHelper.ts
- test/smoke/src/main.ts
[AB#530](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/530)
> [Smoke tests] Implement iOS Debug Expo test

- doc/debugging.md
- src/extension/generalMobilePlatform.ts
- src/extension/ios/iOSPlatform.ts
- src/extension/ios/plistBuddy.ts
- test/extension/generalMobilePlatform.test.ts
This PR fixes scheme parameter ambiguity for iOS debug configuration.
Fixes #989
> Fix scheme parameter ambiguity

- test/smoke/src/areas/explorer/explorer.ts
- test/smoke/src/main.ts
- test/smoke/src/spectron/application.ts
[AB#616](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/616)
> Fix mac tests are getting stuck due to Outline window blocking App.js element in File Explorer

- test/smoke/package.json
- test/smoke/src/areas/debug/debug.ts
- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/debugIos.test.ts
- test/smoke/src/helpers/appiumHelper.ts
- test/smoke/yarn.lock
[AB#617](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/617)
> [Smoke Tests] Replace clipboardy with Electron.clipboard

- test/smoke/docs/run-locally.md
- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/debugIos.test.ts
- test/smoke/src/helpers/configHelper.ts
- test/smoke/src/main.ts
[AB#642](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/642)
> [Smoke tests] Add an ability to run only basic tests for PR builds

- test/smoke/src/main.ts
"ran" is past tense. It should be: "will be run".
> use correct tense

- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/debugIos.test.ts
- test/smoke/src/helpers/appiumHelper.ts
[AB#652](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/652)
> [Smoke tests] Fix for Expo markup for iOS and Android

- src/common/entryPointHandler.ts
- src/extension/rn-extension.ts
[AB#667](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/667)
> Add workspace folders counting to telemetry

- tsconfig.json
This PR adds outDir to tsconfig.json so that we can enable rich code navigation on the repo.
//cc @ruslan-bikkinin
> Adds outDir to tsconfig.json

- README.md
[AB#722](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/722)
> Fix readme markup

- src/debugger/nodeDebugWrapper.ts
- src/debugger/reactNativeDebugEntryPoint.ts
[AB#724](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/724)
> Fix new telemetry objects sending

- package-lock.json
https://www.npmjs.com/advisories/1012
https://github.com/jonschlinkert/mixin-deep/commit/8f464c8ce9761a8c9c2b3457eaeee9d404fa7af9
[AB#727](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/727)
> Fix set-value and mixin-deep vulnerabilities

- test/smoke/src/helpers/configHelper.ts
- test/smoke/src/helpers/setupEnvironmentHelper.ts
- test/smoke/src/main.ts
[AB#738](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/738)
> [Smoke tests] Add versions fixation

- src/common/commandExecutor.ts
https://github.com/microsoft/vscode-react-native/issues/1067#issuecomment-520377506
Make react-native version identifying compatible with @react-native-community/cli
> Fix "react-native -v" for RN v0.60

- src/debugger/nodeDebugWrapper.ts
> Add a fix to create the folder for debuggerWorker.js and app bundle before attaching

- src/common/error/errorStrings.ts
- src/common/error/internalErrorCode.ts
- src/common/telemetryGenerators.ts
- src/common/telemetryHelper.ts
- src/extension/rn-extension.ts
Added telemetry events for checking extension activation errors.
> Telemetry events for checking extension activation errors

- test/smoke/config.json
- test/smoke/resources/PureRNExpoSample/app.json
- test/smoke/src/helpers/setupEnvironmentHelper.ts
- test/smoke/src/main.ts
[AB#810](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/810)
> Bump smoke tests dependencies

- package.json
- test/smoke/config.json
> Optimize activation events

- src/debugger/appWorker.ts
> Add missing semicolon to fix Haul attach issue

- src/debugger/scriptImporter.ts
- src/debugger/sourceMap.ts
- test/debugger/sourceMap.test.ts
- test/smoke/config.json
- test/smoke/resources/ReactNativeSample/App.js
- test/smoke/src/helpers/appiumHelper.ts
[AB#821](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/821)
> Fix sourcemap issue with React Native 0.61

- package-lock.json
https://npmjs.com/advisories/1164
> Fix handlebars security vulnerability

- src/debugger/sourceMap.ts
- test/debugger/sourceMap.test.ts
> Fix debugging issues when some packages was installed on RN 0.61 app

- src/debugger/sourceMap.ts
- test/debugger/sourceMap.test.ts
[AB#826](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/826)
> Improve React Native 0.61 sourcemap parsing approach

- doc/debugging.md
- package.json
- package.nls.json
- src/debugger/direct/directDebugAdapter.ts
- src/extension/debugConfigurationProvider.ts
- test/smoke/resources/launch.json
- test/smoke/src/debugAndroid.test.ts
> Fix Hermes scenarios names, fix port argument handling

- package.json
- package.nls.json
- src/debugger/sourceMap.ts
- src/extension/ios/iOSPlatform.ts
- test/debugger/sourceMap.test.ts
> Fix --project-path React Native command argument handling for iOS

- package-lock.json
https://npmjs.com/advisories/1184
> Fix https-proxy-agent security vulnerability

- README.md
- doc/customization.md
- doc/debugging.md
> Update extension documentation according to React Native local CLI usage

- CHANGELOG.md
- src/extension/exponent/xdlInterface.ts
- src/typings/exponent/xdl.d.ts
- test/smoke/config.json
Fixes #1067
https://github.com/expo/expo-cli/issues/864
> Adapt xdlInterface to new xdl package versions

- package-lock.json
- release/ThirdPartyNotices.txt
https://www.npmjs.com/advisories/1300
> Fix security vulnerabilities

- src/common/packager.ts
- src/extension/commandPaletteHandler.ts
https://github.com/microsoft/vscode-react-native/issues/1159
> Fix getting of project root on Command Palette commands execution

- test/smoke/package/src/debugAndroid.test.ts
- test/smoke/package/src/debugIos.test.ts
- test/smoke/package/src/helpers/appiumHelper.ts
> Fix Expo 36 workflow for Expo Android on macOS

- .vscode/launch.json
> Update extension debug scenarios for direct debugger

- doc/expo.md
> Fixing typo in "helpful"

- src/extension/extensionServer.ts
#1191 
Enhanced telemetry data sending for error 606, added filtering by error code
> Enhanced telemetry in cases if Windows scenario was run without RNW package

- src/cdp-proxy/reactNativeCDPProxy.ts
- src/debugger/rnDebugSession.ts
- tslint.json
#1209
Port of #1107 to new extension version
> Initialization of first breakpoints in the RN app code

- package-lock.json
- package.json
- src/cdp-proxy/debuggerEndpointHelper.ts
- src/cdp-proxy/endpointHelper.ts
- src/cdp-proxy/reactNativeCDPProxy.ts
- src/common/node/promise.ts
- src/debugger/rnDebugSession.ts
Implementation of inspector socket look up functional is based on [vscode-js-debug extension](https://github.com/microsoft/vscode-js-debug) code.
> Implemented inspector socket look up

- package.json
- src/debugger/appWorker.ts
- src/debugger/forkedAppWorker.ts
- src/debugger/rnDebugSession.ts
- src/extension/appLauncher.ts
- src/extension/commandPaletteHandler.ts
- src/extension/ios/iOSPlatform.ts
> Add RN app commands support

- .ci/common-validation.yml
- .ci/master-pipeline.yml
- .ci/pr-pipeline.yml
[AB#941](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/941)
> Fix YAML master pipeline

- package.json
- src/cdp-proxy/reactNativeCDPProxy.ts
- src/debugger/rnDebugSession.ts
[AB#904](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/904)
> Fix applications reloads handling

- src/common/packager.ts
- src/extension/packagerStatusIndicator.ts
https://github.com/microsoft/vscode-react-native/issues/1263
> Increase packager starting time and fix handling of StatusBar items click

- README.md
some links wouldn't work so this fixes them.
> Fix links in Table of Contents, typo

- release/LICENSE.txt
> Update extension license to MIT

- CHANGELOG.md
- package-lock.json
- package.json
- release/ThirdPartyNotices.txt
[AB#973](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/973)
> Prepare for 0.16.0

- package-lock.json
- package.json
- src/debugger/debugSessionBase.ts
bugfix: added existence check for previousAttachArgs object
> deps: Remove redundant dependencies, bump ws

- .ci/nightly.yml
- gulpfile.js
#1295
Example of Preview version generation
> Prepare nightly release for preview version

- .ci/master-pipeline.yml
- .ci/smoke/smoke-tests-linux.yml
- .ci/smoke/smoke-tests-mac.yml
- .ci/smoke/smoke-tests-windows.yml
- src/debugger/jsDebugConfigAdapter.ts
remove smartstep option from debug scenario
> Prepare CI to preview branch

- src/extension/extensionServer.ts
- src/extension/rn-extension.ts
https://github.com/microsoft/vscode-react-native/issues/1306
> Implement launch of the experiment service

- src/extension/android/adb.ts
- test/extension/android/androidPlatform.test.ts
- test/resources/auxiliaryFiles/templateProject/others/android/local.properties
- test/resources/auxiliaryFiles/templateProject/win/android/local.properties
> Fix errors in case of spaces in adb path from local.properties 

- src/common/telemetryGenerators.ts
- src/debugger/appWorker.ts
- src/debugger/forkedAppWorker.ts
- src/debugger/scriptImporter.ts
- src/debugger/sourceMap.ts
- src/debugger/sourceMapsCombinator.ts
> Remove Q from debugger folder

- src/common/node/childProcess.ts
- src/common/node/node.ts
- src/common/telemetryGenerators.ts
- src/extension/android/adb.ts
- src/extension/android/androidPlatform.ts
- src/extension/android/logCatMonitor.ts
- src/extension/android/packageNameResolver.ts
- src/extension/appLauncher.ts
- src/extension/commandPaletteHandler.ts
- src/extension/exponent/exponentHelper.ts
- src/extension/exponent/exponentPlatform.ts
- src/extension/generalMobilePlatform.ts
- src/extension/ios/iOSDebugModeManager.ts
- src/extension/ios/iOSPlatform.ts
- src/extension/ios/plistBuddy.ts
- src/extension/ios/simulatorPlist.ts
- src/extension/launchArgs.ts
- src/extension/openFileAtLocation.ts
- src/extension/reactDirManager.ts
- src/extension/rn-extension.ts
- src/extension/windows/windowsPlatform.ts
- src/extension/windows/wpfPlatform.ts
> Q package removal extension folder

- package.json
- src/extension/packagerStatusIndicator.ts
* improve status indicator and add activation on react-native module
* improve label
* remove restart packager button
Co-authored-by: Yuri Skorokhodov <v-yuskor@microsoft.com>
> Improve Packager status indicator for Preview branch

- test/smoke/package/package.json
- test/smoke/package/yarn.lock
Fix https://www.npmjs.com/advisories/1523
> Fix lodash security vulnerability

- test/smoke/package/package.json
- test/smoke/package/yarn.lock
Fix https://www.npmjs.com/advisories/1523
> Fix lodash security vulnerability (preview)

- src/extension/android/adb.ts
> Fix LogCat monitor error

- .ci/common-validation.yml
- .ci/master-pipeline.yml
- .ci/pr-pipeline.yml
- .ci/smoke/smoke-tests-common-validation.yml
- .ci/smoke/smoke-tests-linux.yml
- .ci/smoke/smoke-tests-mac.yml
- .ci/smoke/smoke-tests-windows.yml
- .vscode/settings.json
> Remove additional TPN copy task

- package.json
- src/common/error/errorStrings.ts
- src/common/error/internalErrorCode.ts
- src/common/node/childProcess.ts
- src/extension/android/androidEmulatorManager.ts
> Fixing child process spawn logging

- src/extension/windows/windowsPlatform.ts
> Add --remote-debugging flag support for RNW

- src/debugger/debugSessionBase.ts
- src/debugger/jsDebugConfigAdapter.ts
> Add filtering for debuggerWorker.js file for searching sourcemaps, fix minor issues

- test/smoke/package/src/helpers/configHelper.ts
- test/smoke/package/src/helpers/vsCodeHelper.ts
- test/smoke/package/src/main.ts
> Use vscode-test for VS Code client downloading

- package.json
> Removes deprecated enableBreakpointsFor API from package.json

- README.md
https://github.com/microsoft/vscode-react-native/issues/1467
> Enhance attach to the debugger documentation

- .vscode/tasks.json
- src/common/launchJsonCompletionHelper.ts
- src/extension/commandPaletteHandler.ts
- src/extension/debuggingConfiguration/launchJsonCompletionProvider.ts
- src/extension/debuggingConfiguration/multiStepInput.ts
- test/smoke/.eslintrc.js
- test/smoke/gulpfile.js
- test/smoke/package/src/debugMacOS.test.ts
- test/smoke/package/src/debugScenariosCreation.test.ts
- test/smoke/package/src/debugWindows.test.ts
- test/smoke/package/src/directDebug.test.ts
- test/smoke/package/src/expoDebug.test.ts
- test/smoke/package/src/helpers/androidEmulatorManager.ts
- test/smoke/package/src/helpers/appiumHelper.ts
- test/smoke/package/src/helpers/iosSimulatorManager.ts
- test/smoke/package/src/helpers/launchConfigurationManager.ts
- test/smoke/package/src/helpers/smokeTestLogger.ts
- test/smoke/package/src/helpers/testApplicationSetupManager.ts
- test/smoke/package/src/helpers/testConfigProcessor.ts
- test/smoke/package/src/helpers/utilities.ts
- test/smoke/package/src/helpers/vsCodeManager.ts
- test/smoke/package/src/localization.test.ts
- test/smoke/package/src/main.ts
- test/smoke/package/src/nativeDebug.test.ts
- test/smoke/package/src/otherTests.test.ts
- test/smoke/package/src/smoke.test.ts
https://github.com/microsoft/vscode-react-native/issues/1462
> Fix ESLint issues in smoke tests

- src/debugger/appWorker.ts
- src/debugger/rnDebugSession.ts
- test/debugger/appWorker.test.ts
Fixes https://github.com/microsoft/vscode-react-native/issues/1486
> Fix attachment to the packager

- README.md
https://github.com/microsoft/vscode-react-native/issues/1512
> Update RNW documentation

- src/common/error/internalErrorCode.ts
- src/common/telemetryGenerators.ts
- src/common/telemetryHelper.ts
- src/extension/rn-extension.ts
> Improve sending error events to Telemetry

- src/common/packager.ts
- src/extension/ios/plistBuddy.ts
https://github.com/microsoft/vscode-react-native/issues/1529
> Fix fast refreshing of React Native apps

- ThirdPartyNotices.txt
- cgmanifest.json
- gulpfile.js
- package-lock.json
- package.json
- src/common/opensslWrapperWithPromises.ts
- src/extension/android/androidContainerUtility.ts
- src/extension/ios/iOSContainerUtility.ts
- src/extension/ios/iOSDeviceTracker.ts
- src/extension/networkInspector/certificateProvider.ts
- src/extension/networkInspector/clientDevice.ts
- src/extension/networkInspector/clientUtils.ts
- src/extension/networkInspector/networkInspectorServer.ts
- src/extension/networkInspector/networkMessageData.ts
- src/extension/networkInspector/requestBodyFormatters/formUrlencodedFormatter.ts
- src/extension/networkInspector/requestBodyFormatters/graphQLFormatter.ts
- src/extension/networkInspector/requestBodyFormatters/imageFormatter.ts
- src/extension/networkInspector/requestBodyFormatters/jsonFormatter.ts
- src/extension/networkInspector/requestBodyFormatters/requestBodyFormatter.ts
- src/extension/networkInspector/requestBodyFormatters/utils.ts
- src/extension/networkInspector/views/inspectorConsoleView.ts
- src/typings/openssl-wrapper/openssl-wrapper.d.ts
https://github.com/microsoft/vscode-react-native/issues/1418
> Network Inspector: add notes about borrowed code

- package-lock.json
- package.json
- package.nls.json
- src/common/error/errorStrings.ts
- src/common/error/internalErrorCode.ts
- src/common/extensionHelper.ts
- src/extension/commandPaletteHandler.ts
https://github.com/microsoft/vscode-react-native/issues/1559
> Implement support of Workspace Trust feature

- src/extension/android/adb.ts
- src/extension/android/androidPlatform.ts
https://github.com/Microsoft/vscode-react-native/issues/324
> Improve debugging on a remote Android device 

- package.json
- package.nls.json
- src/extension/applePlatformDebugModeManager.ts
- src/extension/commandPaletteHandler.ts
- src/extension/ios/iOSDebugModeManager.ts
- src/extension/ios/iOSPlatform.ts
- src/extension/ios/plistBuddy.ts
- src/extension/ios/simulatorPlist.ts
- src/extension/launchArgs.ts
- src/extension/macos/defaultsHelper.ts
- src/extension/macos/macOSDebugModeManager.ts
- src/extension/macos/macOSPlatform.ts
- test/extension/ios/plistBuddy.test.ts
- test/extension/macos/macOSDebugModeManager.test.ts
https://github.com/microsoft/vscode-react-native/issues/1561,
https://github.com/microsoft/vscode-react-native/issues/1586
> Implement debugging mode control for macOS

- src/common/extensionHelper.ts
- src/extension/packagerStatusIndicator.ts
https://github.com/microsoft/vscode-react-native/issues/1591
> Adopt new "createStatusBarItem" API

- src/common/node/childProcess.ts
- src/common/node/fileSystem.ts
- src/common/node/package.ts
- src/common/node/promise.ts
> Migrate to async/await for src/common/node

- src/common/node/promise.ts
- src/extension/exponent/exponentHelper.ts
- src/extension/exponent/exponentPlatform.ts
- src/extension/exponent/xdlInterface.ts
> Migrate to async/await for src/extension/exponent folder

- src/common/node/promise.ts
- src/extension/ios/iOSContainerUtility.ts
- src/extension/ios/iOSDebugModeManager.ts
- src/extension/ios/iOSDeviceTracker.ts
- src/extension/ios/iOSPlatform.ts
- src/extension/ios/plistBuddy.ts
- src/extension/ios/simulatorPlist.ts
> Migrate to async/await for src/extension/ios folder

- src/extension/macos/defaultsHelper.ts
- src/extension/macos/macOSDebugModeManager.ts
- src/extension/macos/macOSPlatform.ts
> Migrate to async/await for src/extension/macos folder

- src/extension/windows/windowsPlatform.ts
> Migrate to async/await for src/extension/windows folder

- src/debugger/debugSessionBase.ts
- test/smoke/package/package.json
- test/smoke/package/yarn.lock
https://github.com/microsoft/vscode-react-native/issues/1629
> Improve error logging on debugging

- src/extension/appLauncher.ts
- src/extension/applePlatformDebugModeManager.ts
- src/extension/commandPaletteHandler.ts
- src/extension/generalMobilePlatform.ts
- src/extension/openFileAtLocation.ts
- src/extension/reactDirManager.ts
- src/extension/rn-extension.ts
> Migrate to async/await for src/extension folder

- src/extension/android/adb.ts
- test/extension/android/androidPlatform.test.ts
https://github.com/microsoft/vscode-react-native/issues/1638
> Improve Android sdk.dir parsing

- CHANGELOG.md
- package-lock.json
- package.json
- release/ThirdPartyNotices.txt
_Changes:_
- Bumped extension version to 1.7.0
- Added description of changes to `CHANGELOG.md` file
- Updated Third Party Notices
> Prepare for 1.7.0

- src/cdp-proxy/debuggerEndpointHelper.ts
- src/debugger/direct/directDebugSession.ts
https://github.com/microsoft/vscode-react-native/issues/1693
> Fix debugging on reloading a Hermes app

- README.md
https://github.com/microsoft/vscode-react-native/issues/1714
> Enhance Network inspector requirements documentation

- gulpfile.js
- src/debugger/sourceMap.ts
- test/debugger/sourceMap.test.ts
https://github.com/microsoft/vscode-react-native/issues/1728
> Fix sourcemaps handling

- CONTRIBUTING.md
- README.md
- test/smoke/docs/run-locally.md
> Documentation update for configuring the smoke test machines

- .gitignore
- .vscode/tasks.json
- package-lock.json
- package.json
- test/index.ts
- test/mochaReporterConfig.json
- test/smoke/package/.mocharc.js
- test/smoke/package/mochaReporterConfig.json
- test/smoke/package/package.json
Use mochawecome as reporter of unit test and smoke test. It will show the test report more intuitive and make failure  investigation more convenient
> update report for test

- package-lock.json
> Fix npm install issue: update package-lock.json

- test/smoke/package/resources/HermesReactNativeSample/build.gradle
> Update smoke test hermes app config

- README.md
Update documentation for output log color customize
> Update documentation for output log color customize

- test/common/utils.test.ts
> remove filter

- src/extension/exponent/exponentPlatform.ts
- test/smoke/docs/run-locally.md
> Update Linux environment setup documentation and fix code format issue

- .vscode/launch.json
- .vscode/settings.json
- test/localization/localization.test.ts
- test/localization/runTest.ts
Update localization test for zh-cn
> Update localization test for zh-cn

- CONTRIBUTING.md
> Update documentation for gulp task new changes

- gulp_scripts/release.js
> [Bug] Nightly release: UnhandledPromiseRejectionWarning: ReferenceError: extensionName is not defined

- .vscodeignore
- test/mochaReporterConfig.json
> [Feature] Remove unused file from webpack

- src/cdp-proxy/debuggerEndpointHelper.ts
- tools/gulp-extras.js
> [Feature] Using CodeQL alert suppressions rather than LGTM alert suppressions

- test/localization/localization.test.ts
- test/localization/runTest.ts
> [Feature] Workaround localization test issue caused by Vscode 1.76.0

- release/ThirdPartyNotices.txt
> Cleanup and update 3rd party notices file

- src/extension/android/adb.ts
Fix for https://github.com/microsoft/vscode-react-native/issues/1988
> Fix getting android sdk path logic in local.properties file

- src/extension/exponent/xdlInterface.ts
> [Bug] Fix unexpected internal error related to 'reactNativeVersionWarnings'

- package-lock.json
> [Feature] Bump minimatch version to 3.0.5

- package-lock.json
> Bump nanoid (not including the package under test) and yangs-parser

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> Prepare for 1.12.1

- CHANGELOG.md
- package-lock.json
- package.json
> Prepare for 1.12.2

- package-lock.json
- package.json
- test/resources/processExecution/recorder.ts
fixing [#2269 ](https://github.com/microsoft/vscode-react-native/issues/2269)
> Fix unsafe shell command constructed from library input in test
