microsoft/vscode-react-native

- src/common/ios/iOSDebugModeManager.ts
- src/debugger/ios/iOSPlatform.ts
When enabling debug mode on the iOS simulator, we attempt to modify a plist file backing an NSUserDefaults object. This plist file is written to by the app at various times, and this would sometimes overwrite our change.
With this fix, we start the app to ensure the file is created, then we stop the app to avoid a race condition. We need to wait a moment to ensure that the app is completely closed, then we write to the file and restart the app. Simply relaunching the app is not sufficient, we need to re-install the app or it does not pick up the changes.
Fixes #44
> Fixing a race condition

- src/debugger/appWorker.ts
Described in #91, https://github.com/facebook/react-native/commit/64d56f34b779de94f251f4b443463cbfe790912d introduces a breaking change that requires `role` and `name` query parameters as part of the /debugger-proxy url. This is a breaking change introduced in `0.21.0-rc` of React Native. This is a required patch to retain compatibility in the upcoming full release of `0.21.0`.
An example can be found in https://github.com/facebook/react-native/commit/64d56f34b779de94f251f4b443463cbfe790912d#diff-6ec5b06d4c2f30dd3f47c1eaaee08c3dR28 of connecting with the new query parameters
> Bugfix - Debugger URL query parameter requirements

- gulpfile.js
- tools/checkCasing.js
Since we've had a few instances of capitalisation typos in imports, I'm adding this build step to automatically check the source code. It goes over all `.ts` files under `src` and checks all `import [...] from "[...]";` lines. If the import is a relative path, it ensures that the destination is a `.ts` file at that location with that exact name.
> Adding a step to check imports use correct names

- README.md
I hadn't installed an extension in VS Code in months and had forgotten how when it came time to install the React Native extension. In the "Getting started" section, I linked the first step to the official VS Code instructions for anyone else in a similar new-to-Code situation.
> Link to information about installing extensions.

- src/common/packager.ts
The packager is now always launched from the extension process, so checking for this.packagerProcess is good enough.
> Now we print the packager warning only if it wasn't started from VS Code

- errorStrings/errorStrings.json
- src/common/commandExecutor.ts
- src/common/node/childProcess.ts
(Porting over some must-fix items from refactor branch)
> Error strings should print useful information about the command being run (command with args)

- SampleApplication/package.json
- src/debugger/android/androidPlatform.ts
This PR fixes a bug introduced when we merged the "Stop on Android Error" feature.
> Now the launch when multiple devices are available, and stop on Androiderror features work correctly together

- src/test/debugger/sourceMap.test.ts
Updated test to use Unix style path (which we expect), and not to use path.relative.
> Fix Windows Test Path Issue

- package.json
- src/common/error/errorHelper.ts
- src/common/ios/plistBuddy.ts
- src/common/ios/simulatorPlist.ts
- src/common/ios/xcodeproj.ts
- src/common/node/childProcess.ts
- src/common/telemetry.ts
- src/debugger/android/androidPlatform.ts
- src/debugger/appWorker.ts
- src/debugger/ios/compiler.ts
- src/debugger/ios/iOSPlatform.ts
- src/debugger/nodeDebugWrapper.ts
- src/extension/commandPaletteHandler.ts
- src/extension/intellisenseHelper.ts
- src/test/common/extensionMessaging.test.ts
- src/test/common/ios/plistBuddy.test.ts
- src/test/common/ios/simulatorPlist.test.ts
- src/test/common/ios/xcodeproj.test.ts
- src/test/debugger/appWorker.test.ts
- src/test/index.ts
- tslint.json
Turned off object-literal-sort-keys because it asks to change:
{ message: ..., args: ... } to { args: ..., message: ... }
no-keyword-named-variables doesn't seem to exist any more
added the trailing commas because we had the option turned on, but we used an old tlisnt version that didn't run that check.
Didn't update vscode because it breaks stuff (We should create a small task to update that one).
> Upgraded all dev dependencies to their latest version

- .vscode/launch.json
- gulpfile.js
- package.json
* Added Run mocha as a new Debug target to debug the tests inside VS Cod
* Now we support a --pattern parameter in gulp test that can filter tests by case name
> Now we can debug mocha tests from VS Code, and filter test with gulp test --pattern <pattern>

- src/common/android/packageNameResolver.ts
- src/common/hostPlatform.ts
- src/common/node/fileSystem.ts
- src/common/node/promise.ts
- tsconfig.json
- tslint.json
* When creating a project with react-native init, it converts the name to lower case. We are changing getDefaultPackageName to match that behavior.
* Now we use the noFallthroughCasesInSwitch typescript option instead of the tslint option no-switch-case-fall-through that is going to be deprecated.
* Created some utility methods that are used by the run-android tests
> Added some methods needed for the run-android tests. Made other small fixes too.

- src/common/node/childProcess.ts
We can use a convention that each time we assign a node module to an instance variable, we prepend 
"node" prefix to the node module to make clear our intent.
> Renamed imported child_process to nodeChildProcess

- src/debugger/ios/deviceRunner.ts
- src/test/debugger/ios/deviceRunner.test.ts
- src/test/resources/processExecution/simulator.ts
Fixes #204 
When we changed to using a member variable childProcess we didn't account for `function() {}` style functions changing `this`. With this PR I convert relevant functions to `() => {}` style functions which preserve `this`.
> Fixing an issue with 'this' in ios/deviceRunner

- gulpfile.js
- src/test/resources/fakeExtensionMessageSender.ts
* Using @dlebu's code to fix this issue
* Tested it with both working and broken source and it seems to work for both cases, although it prints a full stack trace when there is an error
> Updated gulpfile so 'gulp test' will fail on errors

- gulpfile.js
Small fix to remove the "manual" args stripping in the gulpfile and replace it with minimist (which is already built-in)
fixes #201
> remove args stripping and use minimist

- README.md
- src/debugger/ios/deviceDeployer.ts
As discussed in #211 this PR fixes the error handling when `ideviceinstaller` is not installed and the app should be launched on target `device`
fixes #211
> Fix error handling of not-installed ideviceinstaller when running on device

- scripts/atom
- scripts/atom.cmd
- src/common/error/internalErrorCode.ts
- src/common/extensionMessaging.ts
- src/common/packager.ts
- src/common/remoteExtension.ts
- src/extension/extensionServer.ts
- src/extension/openFileAtLocation.ts
React native provides a `GUI` (in the running simulator or device) with the stack trace when it encounters an error. If you click on a file name in that interface it should open up the editor of your choice with the selected file at a given line number. Currently `react native` supports a list of editors. This PR adds `vscode` to that list.
This PR is intended to work with the current version of `react native`. When the react native repo merges this PR:
https://github.com/facebook/react-native/pull/7757
> Support opening vscode in file at line from react native

- src/extension/intellisenseHelper.ts
When intellisense is setup it checks if VSCode's installed version supports salsa. If it's not then it shows a prompt to restart VSCode so appropriate configurations can be made. This check was done in all steps of the setup except for the one where salsa was enabled.
> Avoid prompt to restart VSCode after configuring react-native typings where possible

- src/common/configurationReader.ts
- src/common/error/internalErrorCode.ts
- src/extension/intellisenseHelper.ts
- src/extension/settingsHelper.ts
Instead of reading the workspace configuration by parsing the `settings.json` file use the API provided by VSCode to do so. This lets the user have the same syntax as the one VSCode permits in their global settings file.
For legacy versions, whenever we need to update the user settings, the extension will show an information message telling the user to update the workspace `settings.json` manually.
> Use vscode API to read configurations

- src/extension/settingsHelper.ts
When trying to get the Typescript Tsdk it could be in the configuration but set as null. This is an amend to https://github.com/Microsoft/vscode-react-native/pull/241 that didn't take that into account. 
Without this fix, the code does configure intellisense correctly but it shows an error message to the user telling him that intellisense was not configured. This every time it tries to configure it.
> Fix issue where typescript tsdk is in configuration but set to null

- README.md
- src/common/extensionMessaging.ts
- src/extension/openFileAtLocation.ts
In Windows and OS X file paths are case insensitive, but case preserving. Therefore we can refer to the same path with different case combinations. If we are hashing the workspace path, we need to make sure that it will always be the correct one, no matter what case it is.
NOTE. This fix leaves an issue exposed where, if you are in a linux machine, and you have two simultaneous workspace open that have the same path, but only differ on casing, then the socket will always talk to one of them.
> Downcase workspace path before hashing for socket pipe name

- src/common/reactNativeProjectHelper.ts
Currently, for determining if a project is a react-native project, only the package.json is searched for the dependency 'react-native', Since it could be also a library which brings react-native, we have to check sub-dependencies too.
This PR introduces searching of sub-dependencies at a customizable level / depth. I added a test but was not sure how to implement, so it uses local directories. I didn't want to add it to this PR therefore.
> React Native can also be a sub-dependency

- src/common/commandExecutor.ts
- src/common/reactNativeProjectHelper.ts
https://github.com/Microsoft/vscode-react-native/pull/253 added some functionality to check for react native version using `react-native -v` command.
Because it was using `spawnReactCommand`, every time we checked for the version, some logs would appear to the user telling it the command was run, adding unnecessary stuff to the user's view.
This PR refactors this logic to do the same but avoid logging the message to the user.
> Don't show a message each time we check for react-native version

- package.json
- src/common/log/logHelper.ts
- src/common/log/loggers.ts
- src/debugger/launcher.ts
- src/debugger/nodeDebugAdapter.d.ts
- src/debugger/nodeDebugWrapper.ts
- src/debugger/reactNativeDebugEntryPoint.ts
The logic for running the debugger was mixed between a process running in the debugger side (`nodeDebugAdapterWrapper.js`) and a process running in the program being debugged (`launcher.js`).
This PR is a refactor of that logic, trying to run as much code as possible in the debugger side. Also making the appropriate distinctions between the attach and the launch request, and trying to use more OOP to add legibility to the code.
> Refactor nodeDebuggerAdapter wrapper

- README.md
- package.json
- src/common/android/androidPlatform.ts
- src/common/packager.ts
- src/debugger/appWorker.ts
- src/debugger/generalMobilePlatform.ts
- src/debugger/ios/iOSPlatform.ts
- src/debugger/nodeDebugAdapter.d.ts
- src/debugger/nodeDebugWrapper.ts
- src/debugger/platformResolver.ts
- src/debugger/scriptImporter.ts
- src/test/debugger/appWorker.test.ts
- src/typings/ws/ws.d.ts
If user has started the debugger outside of VSCode, and wants to debug, the only way to go was using chrome dev tools. With this PR, the user can attach a VSCode debug session to a running packager.
One scenario when this is useful is when trying to debug native components in iOS using Xcode and have the need to debug the javascript code, where VSCode comes up handy.
> User can attach to packager ran outside vscode to debug

- README.md
- src/extension/intellisenseHelper.ts
If there are already typings for the react-native project we don't want to overwrite them. This let's VSCode have a default typing but give the opportunity to the user to update them or use any typings as desired.
> don't overwrite existing react and react-native typings

- errorStrings/errorStrings.json
- src/common/error/internalErrorCode.ts
- src/common/interProcessMessageSender.ts
- src/test/common/extensionMessaging.test.ts
If the IPC channel fails, we now include the reason for the failure for easier debugging. If it fails specifically due to an ENOENT when trying to find the pipe, we present a custom error message covering some common reasons.
> Improving IPC error reporting

- gulpfile.js
- src/common/ios/plistBuddy.ts
- src/common/ios/xcodeproj.ts
- src/common/node/fileSystem.ts
- src/debugger/ios/compiler.ts
- src/debugger/ios/deviceDeployer.ts
- src/test/common/ios/plistBuddy.test.ts
- src/test/common/ios/xcodeproj.test.ts
We now follow similar logic to react-native's cli when performing iOS builds, and pick either the .xcodeproj or .xcworkspace, whichever we find first.
Fixes #264
> Updating project detection to work with workspaces

- package.json
- src/common/android/androidPlatform.ts
- src/common/launchArgs.ts
- src/common/reactNative.ts
react-native run-android allows a --variant option, and we now expose that through our launch.json
Fixes #270
> Adding support for --variant

- src/extension/outputChannelLogger.ts
- src/extension/rn-extension.ts
Instead of creating an output channel once our extension is loaded, with this change we defer it to when it is required. When the output channel is created it triggers the output pane to come into view, so by defering it we avoid cluttering the screen until there is something worth looking at.
Fixes #258
> Defer output channel conversion

- package.json
We will be using this package shortly, and it is in our npm-shrinkwrap to make sure we use the right version. Without it also being a dependency, packaging fails due to npm list failing.
> Adding strip-json-comments to package.json

- errorStrings/errorStrings.json
- package.json
- src/common/error/internalErrorCode.ts
- src/common/extensionMessaging.ts
- src/common/packager.ts
- src/extension/commandPaletteHandler.ts
- src/extension/extensionServer.ts
- src/extension/rn-extension.ts
It's in addition to the existing "start packager" and "stop packager" commands. It also resets the cache when (re)starting, which can fix up various issues like source map not being updated for TypeScript apps, etc.
> Added a "restart packager" command.

- src/common/exponent/exponentHelper.ts
- src/common/exponent/exponentPlatform.ts
- src/common/generalMobilePlatform.ts
- src/common/packager.ts
- src/extension/extensionServer.ts
If the packager is started from the command palette, and then the debugger is started, kill the first packager. VSCode controls that packager too, and it would be much less confusing.
* Moved packager type check logic (which prevents packager restart) from generalMobilePlatform to extensionServer
* Indicate when packager is actually stopped to prevent possible incorrect Status Bar state in case of an internal error
* Expose Packager PackagerRunAs property
* Updated exponentPlatform.startPackager log message to not to be confused with React Native packager
* Adds missing return promise in configureExponentEnvironment chain
> Stop packager on React/Exponent environment switch

- src/extension/tsconfigHelper.ts
Enable `allowSyntheticDefaultImports` option by default for new projects to enable intellisense for React typings when the whole React namespace is being imported using `import React from 'react'` syntax.
This fixes #322
> Enable intellisense for React namespace

- README.md
- src/extension/outputChannelLogger.ts
- src/extension/rn-extension.ts
- src/extension/settingsHelper.ts
Users are reporting issues on GitHub that would be easier to debug if we exposed our verbose logging. The user could then copy the logs and send them to us to make it easier to debug issues they're having. We should expose a flag to enable verbose logging in our extension.
> Expose logs

- src/debugger/sourceMap.ts
- src/test/debugger/sourceMap.test.ts
React-native packager produces an inline sourcemaps for each module in the bundle even if `.babelrc` has `sourceMaps: true`
This leads to debugging failure when we're trying to get sourcemap URL from the bundle and expect it to be a file URL, rather than data URL
> Improve source map URL regex to ignore inline maps

- CHANGELOG.md
- src/debugger/appWorker.ts
React-native does not expect that 'require' exists in the ambient context, and attempts to overwrite it with a require.js require. However, in node 7 this replacement fails, so we should simply not provide one in the first place so the require.js require is picked up.
Fixes #370
> Removing 'require' from appworker sandbox

- src/common/android/androidPlatform.ts
- src/common/outputVerifier.ts
- src/debugger/ios/iOSPlatform.ts
- src/debugger/nodeDebugAdapter.d.ts
- src/debugger/nodeDebugWrapper.ts
This PR adds `"variant"` option to launch config, that complies with `--variant` option for `react-native run-android` command.
Also for the cases when `react-native run-android` is not able to run the app on device/simulator it adds a descriptive error message. This is needed as react-native does not yet support launching apps with application Id other than specified in Android manifest (see https://github.com/facebook/react-native/issues/8308)
> Pass Android build variant to react-native

- src/debugger/nodeDebugWrapper.ts
This fixes the issues w/ starting/reloading app (introduced in #390) due to debug adapter conecting to stale app worker.
/cc @MSLaguana 
Also as a side note - I'm still seeing Node's `GLOBAL` deprecation message, but I doubt we could avoid it because `GLOBAL`'s setter is also configured to emit this warning (see https://github.com/nodejs/node/blob/master/lib/internal/bootstrap_node.js#L203-L219)
> Fix race conditions when reloading app on device

- package.json
Reword labels for launch configurations so they can be clearly identified as React Native debug configurations.
> Rename launch.json snippets

- src/debugger/appWorker.ts
- src/test/debugger/appWorker.test.ts
This PR fixes the following 2 issues:
- Node's `'GLOBAL' deprecation warning` caused by accessing `global.GLOBAL` property
- Missing `global.__debug__.require` which is intended to hold original Node's `require`
This should fix #398 and #406
> Fix regressions in app worker introduced after moving to 'node2' debugger

- src/common/exponent/exponentHelper.ts
- src/common/exponent/xdlInterface.ts
- src/common/packager.ts
Couldn't resolve asset's modules in exponent apps due to we haven't passed packager options from `exp.json` to react-native packager.
Related issues: https://github.com/Microsoft/vscode-react-native/issues/414, https://github.com/Microsoft/vscode-react-native/issues/407
> Fix bug with loading assets in exponent and upgrade XDL

- src/debugger/nodeDebugAdapter.d.ts
- src/debugger/nodeDebugWrapper.ts
Could not reproduce this issue https://github.com/Microsoft/vscode-react-native/issues/399, but there is a way to catch unhandled exception by overwriting `setBreakpoints` method that passes on empty breakpoints array in case of failure.
> Avoid unhandled rejections when breakpoints are being set up unsuccessfully

- src/common/ios/xcodeproj.ts
- src/test/common/ios/xcodeproj.test.ts
I modified Xcode project/workspace file detection to prefer workspaces over project files (this is more consistent with the way react-native's cli tools work). 
This also plays nicely with CocoaPods when the workspace and app project file are in the same directory.
For reference: https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/local-cli/runIOS/__tests__/findXcodeProject-test.js#L31
> Prefer xcworkspace over xcodeproj when launching xcodebuild.

- README.md
The current README instructs users to set `sourceMaps = true` in `.babelrc`. While likely obvious that this implies `sourceMaps: true` to users experienced with the babel world, it may be clearer to state so explicitly.
> Updated README .babelrc instructions

- package.json
- src/common/exponent/exponentPlatform.ts
- src/extension/commandPaletteHandler.ts
- src/extension/extensionServer.ts
- src/extension/qrCodeContentProvider.ts
- src/extension/rn-extension.ts
This PR adds functionality that shows QR code with URL of Expo app when Expo packager starts, so the app could be opened by scanning that code.
See screenshot below for the example of how it'll look like
This implements #423
> Implement logic for displaying Expo's QR code

- npm-shrinkwrap.json
Adding missing entry as it seems to be causing problems w/ internal CI. It also fails to compile on some machines, even though works for me.
> Update npm_shrinkwrap to include new dependency

- package.json
TSC 2.3 has [bug](https://github.com/Microsoft/TypeScript/issues/15819) which generate `use strict` in top of all comments. I suggest stick with typescript@2.2.2 until they will not fix it
> Fix check-copyright gulp task. Stick with tsc version 2.2.2

- gulpfile.js
gulpfile.js has mixed single and double quotes style. All *.ts files use double quote style. Default ESLint rule also recommend to use double quote.
This PR changed all single quotes to double quotes in gulpfile to follow unified code style.
> Double quotes in gulpfile to follow unified code style

- gulpfile.js
This fix allow set breakpoints in TS files (extension and debugger)
> Fix gulp-sourcemap generator

- src/extension/android/logCatMonitor.ts
- src/extension/outputChannelLogger.ts
There are 2 options to fix #433:
- Dispose [output channel](https://code.visualstudio.com/docs/extensionAPI/vscode-api#OutputChannel) before each run
- Output new logs to same channel
Because of [problems with timeouts](https://github.com/Microsoft/vscode/issues/6252) I suggest second option
> Reuse log channel for LogCat

- .vscode/launch.json
- gulpfile.js
To increase build time during development.
`check-imports` and `check-copyright` tasks useless during development but take about 14 seconds to perform.
> Add quick-build gulp task

- package.json
- src/common/launchArgs.ts
- src/debugger/ios/compiler.ts
- src/debugger/ios/iOSPlatform.ts
- src/debugger/nodeDebugWrapper.ts
This PR addresses the issue https://github.com/Microsoft/vscode-react-native/issues/434
Per the noted issue, non trivial Xcode projects often define customized "schemes" and it is desirable to be able to specify them when building. 
I extended the "launch" configuration attributes to include an optional "scheme" property.  While I considered overloading the Android-centric "variant" property, in the end I believe providing a term-specific property is more clear to the user.
If this "scheme" property is provided in a launch.json configuration, its value is passed through to the `react-native run-ios` command in the simulator case, or to `xcodebuild` otherwise.   I tested both cases.
I did not explicitly create a test for this but I'd be happy for guidance on how this would work.  I …
> allow “scheme” to be defined and passed through to xcodebuild

- .vscode/launch.json
- src/debugger/nodeDebugAdapter.d.ts
- src/debugger/nodeDebugWrapper.ts
- src/debugger/reactNativeDebugEntryPoint.ts
When we "suppress" "terminate" event, client stays in "stopped" state.
I suggest send "continued" event to client instead of "terminated"
> Fix "Error processing 'continue'"

- npm-shrinkwrap.json
- package.json
- src/debugger/sourceMap.ts
- src/debugger/sourceMapsCombinator.ts
This PR enables typescript debugging + setting breakpoints in original typescript sources by implementing a logic to process react-native's bundle map and update source files mappings to point to original Typescript files.
This also works with any generated JS files that have source maps, not only with ones gennerated by Typescript. This also doesn't require to provide any special options to RN packager and hopefully would work with any future RN versions as it doesn't depend on any RN-specific features.
This resolves #441, resolves #328
> Allow to set breakpoints in original source files

- src/debugger/forkedAppWorker.ts
Since react-native@0.45 when RN App emit message for debugWorker it doesn't wait response for `"method":"executeApplicationScript"` and emit new messages before app script executed
#459
> Queued messages from RN App until app script will be executed

- README.md
React Native uses Metro bundler now, the URL in readme was pointing to code that no longer exists.
> Update README.md broken link to React Packager

- src/common/commandExecutor.ts
- src/extension/commandPaletteHandler.ts
- src/test/common/commandExecutor.test.ts
The bug is a regression introduced in 94cd514970 and was caused by passing undefined arg to `child_process.spawn` where it expects an array of string. We need to consider enabling `strictNullCheck` option in tsconfig to avoid similar issues in the future.
/cc @iToys
Fixes #500
> Fix 'react-native run-ios' failure from command palette

- .gitignore
- gulpfile.js
- src/debugger/sourceMapsCombinator.ts
- src/test/debugger/assets/hello.ts
- src/test/debugger/sourceMapsCombinator.test.ts
> Patch for multi disk support on Windows(TS Sourcemap)

- gulpfile.js
- npm-shrinkwrap.json
- package.json
It appeared that gulp-mocha> 4.0 runs tests in a forked process so instanbul is not able to catch up coverage data
See https://github.com/SBoudrias/gulp-istanbul/issues/115
> Downgrade gulp-mocha to work with istanbul

- src/common/packager.ts
This should fix annoying and misleading error message in case when application's entry point filename differs from regular `index.ios|android.js`. In that case instead of trying to fetch bundle from packager we would just skip prewarming.
Fixes #432
> Skip prewarming cache in case when guessed entry point doesn't exist

- src/debugger/sourceMapsCombinator.ts
According to example from #561, debugging is not working properly when trying to set breakpoints in Haxe `.hx` files, it happens because Haxe adds `sourceRoot` with value `file:///` to .map file and it doesn't play well in our .map paths resolution for Windows paths. This PR fixes mapping for Haxe projects.
> Fix map issue on Windows when sourceRoot is used in map file

- doc/expo.md
The link back to the main Readme from Expo.md was broken because of a typo.
> Fixed broken link in expo.md

- src/common/reactNativeProjectHelper.ts
- src/debugger/appWorker.ts
- src/debugger/scriptImporter.ts
- According to #588, haul `debuggerWorker` url is located in package root, not in `/debugger-ui` like RN packager >= 0.50.0.
- Current haul `debuggerWorker` uses `fetch`, so PR provides `fetch` replacement to patched `debuggerWorker`
> Fix haul project debug

- src/common/outputVerifier.ts
- src/extension/extensionServer.ts
- test/extension/android/androidPlatform.test.ts
> Ignore success patterns case when matching

- package.json
- src/common/hostPlatform.ts
- src/common/targetPlatformHelper.ts
- src/extension/launchArgs.ts
- src/extension/platformResolver.ts
- src/extension/windows/windowsPlatform.ts
Resolve #614 
For debugging `react-native-windows` add new `launch.json` configuration:
```
{
"name": "Debug Windows",
"program": "${workspaceRoot}/.vscode/launchReactNative.js",
"type": "reactnative",
"request": "launch",
"platform": "windows",
"sourceMaps": true,
"outDir": "${workspaceRoot}/.vscode/.react"
},
```
> Debugger for react-native-windows

- package.json
This PR prevents extension to be activated at VS Code start and force it to do that only 
* if opened directory has react-native package installed
* on debug session start
* if one of this extension commands was executed
> Add more specific activationEvents

- src/common/reactNativeProjectHelper.ts
- src/debugger/forkedAppWorker.ts
- src/debugger/scriptImporter.ts
- src/debugger/sourceMap.ts
Unfortunately RN54.x doesn't generate inlined ref to sourcemaps (issue with Metro bundler, should be fixed in future versions). So this PR focused to solve issues for current users unless it will not be fixed with new RN release. 
If you have any ideas how to fix this other way or see areas of improvements I'm all ears!
> fix-issue-with-sourcemaps RN54.x

- src/debugger/nodeDebugWrapper.ts
Because we re-use `attachRequest()` in launch() request and use `super.dispatchRequest({command: "attach", ...}); ` to invoke the attach() method. The response emitted will say "attach" even for "launch" request.
Now we directly invoke the `attach()` method in the  `attachRequest()` method and manually send back the response.
> Fixes a bug that the response of "launch" request will say "attach".

- src/common/error/errorStrings.ts
- src/extension/commandPaletteHandler.ts
- src/extension/rn-extension.ts
This PR fixes error logs in case of running Palette commands from inside non-RN project.
#652 
Command "Publish to Exponent"
before
after
Command "Reload App"
before
after
Command "Run iOS on Device"
before
after
Command "Show Dev Menu"
before
after
> Fix error logging for palette commands

- npm-shrinkwrap.json
- package.json
- src/extension/settingsHelper.ts
This PR prevents such warnings to be appeared during extension work:
```[vsmobile.vscode-react-native] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'react-native-tools.logLevel', provide the URI of a resource or 'null' for any resource.```
> Fix "Accessing a resource scoped configuration without providing a resource is not expected" warning

- src/debugger/appWorker.ts
This PR prevents leaking process.versions and process.versions from debugger process to
worker because pure React Native doesn't do that and some packages as js-md5 [rely on this behavior](https://github.com/emn178/js-md5/blob/master/src/md5.js#L20).
Resolves #747.
> Forceibly remove process.versions for debugger worker

- src/common/node/fileSystem.ts
- src/extension/android/adb.ts
- src/extension/android/androidPlatform.ts
- src/extension/android/logCatMonitor.ts
- src/extension/commandPaletteHandler.ts
- src/extension/ios/iOSPlatform.ts
- test/extension/android/androidPlatform.test.ts
- test/resources/reactNative022.ts
This PR add ability to use Android SDK location defined in `sdk.dir` at `android/local.properties` if exists.
Relates to #688.
> [Android] Add reading SDK location from local.properties

- src/debugger/forkedAppWorker.ts
- src/debugger/nodeDebugWrapper.ts
- test/debugger/appWorker.test.ts
> Use fork instead of spawn for AppWorker

- src/extension/android/androidPlatform.ts
- src/extension/generalMobilePlatform.ts
- src/extension/ios/iOSPlatform.ts
This PR fixes critical issue with android debugging introduced in 0.6.14.
#777
> FIx incorrect runArguments assignment

- src/debugger/forkedAppWorker.ts
- test/debugger/appWorker.test.ts
Changes previously introduced in https://github.com/Microsoft/vscode-react-native/pull/760 breaks input/output channels between app worker and Debug Console, so this PR reverts them.
> Return spawn instead of fork

- package.nls.json
Extension doesn't provide code-hinting anymore for React Native so we should remove any mentions of it.
> Update extension description

- .vscode/launch.json
- test/smoke/src/main.ts
Add `--skip-setup` startup argument to skip tests setup
> [Smoke tests] Smoke test debugging improvement

- package.nls.json
Just a minor wording improvement, changing
```
Run Android on Simulator
```
to
```
Run Android on Emulator
```
**Reason**: [Android is using emulators](https://developer.android.com/studio/run/emulator), not simulators.
Even though it _sounds_ similar, the underlying mechanism is very different: On Android, a real image of the actual operating system is _emulated_ (like a virtual machine), whereas on iOS, the simulator _simulates_ the environment that an app would use on a real device.
This PR fixes the wording in the Command Palette.
> Fix "Run Android on Emulator" wording

- test/smoke/.gitignore
- test/smoke/src/areas/debug/debug.ts
- test/smoke/src/areas/explorer/explorer.ts
- test/smoke/src/debugAndroid.test.ts
- test/smoke/src/helpers/appiumHelper.ts
- test/smoke/src/helpers/setupEnvironmentHelper.ts
- test/smoke/src/main.ts
- test/smoke/src/spectron/application.ts
Add VS Code temporary folder to artifacts folder
Replace drop-win/.gitkeep to correct folder
Add test logs folder to clean up
Fix css selectors for debugging panel due to VS Code 1.33 release
Add retries for expoURL get method
Increase timeout for opening React Native DevMenu for **all platforms**
> [Smoke tests] Tests refactoring, fix css selectors for VS Code 1.33

- README.md
This is a simple commit based on #985 I'd like to add this to the known issues. Since I suspect it could be a common error.
> [Docs] Adding a bug to known issues in the readme for adding configuration in VSCode

- src/debugger/forkedAppWorker.ts
Fixes #1000 
[Node.js no more supports `--debug-brk` arg in Node.js 12](https://github.com/nodejs/node/releases/tag/v12.0.0)
[`--debug-brk` deprecated since `v7.7.0`](https://nodejs.org/en/docs/guides/debugging-getting-started/#legacy-debugger )
[AB#606](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/606)
> Fix for node debugging process arguments due to end of life of --debug-brk arg in Node 12

- package.json
- src/extension/debugConfigurationProvider.ts
- src/extension/rn-extension.ts
This PR implements the first part of #830
Initial configurations in `package.json` are replaced by DebugConfigProvider class with using QuickPick UI to pick needed debug configurations. 
Required VS Code version is bumped to 1.26
Preview of how it looks: 
[AB#683](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/683)
> Add DebugConfigProvider for configuring initial debug configurations

- doc/debugging.md
- package.json
- package.nls.json
- src/common/remoteExtension.ts
- src/debugger/nodeDebugWrapper.ts
- src/extension/debugConfigurationProvider.ts
- src/extension/rn-extension.ts
- test/smoke/resources/launch.json
This PR implements the second part of #830.
Two properties were removed from initial debug scenarios:
* `sourceMaps` debug scenario property is now always set to true if not defined explicitly.
* `outDir` property was completely removed as not used in the code.
[AB#683](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/683)
> Simplify basic debug scenarios

- test/smoke/src/helpers/configHelper.ts
- test/smoke/src/helpers/vsCodeHelper.ts
[AB#739](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/739)
> [Smoke tests] Add process.env.NIGHTLY parameter processing for nightly builds

- CHANGELOG.md
- package-lock.json
- package.json
- release/ThirdPartyNotices.txt
[AB#819](https://dev.azure.com/vscode-webdiag-extensions/5c2c3798-7e49-49f6-b45f-77d9c69636c6/_workitems/edit/819)
> Prepare for 0.11.2

- src/debugger/direct/directDebugAdapter.ts
Fixes issue №3 from https://github.com/microsoft/vscode-react-native/issues/1099 
https://github.com/facebook/hermes/issues/168
> Fix displaying of VM_unknown calls in Call Stack for Hermes debugger

- package.json
- package.nls.json
- src/extension/debugConfigurationProvider.ts
Implements [https://github.com/microsoft/react-native-windows/issues/3593](https://github.com/microsoft/react-native-windows/issues/3593)
When creating a launch.json, the new configuration is presented like this:
When editing the launch.json, the new configuration is presented like this (after pressing the "Add Configuration..." button):
First time contributing, I apologize if everything is wrong!
> Add Windows configuration to the presets

- src/common/error/errorStrings.ts
- src/common/error/internalErrorCode.ts
- src/extension/extensionServer.ts
- src/extension/windows/windowsPlatform.ts
Based on follow up comments in [https://github.com/microsoft/react-native-windows/issues/3593](https://github.com/microsoft/react-native-windows/issues/3593).
Prints the following warning message: `It appears you don't have react-native-windows installed. Go to https://github.com/microsoft/react-native-windows#getting-started for more info.` when the user tries to debug windows and it seems that react native windows is not installed.
Previously, only the following was printed out: `error Unrecognized command "run-windows".`
> Show clearer message when debugging windows without react native windows installed

- src/common/node/childProcess.ts
- src/extension/ios/plistBuddy.ts
- test/smoke/package/config.json
- test/smoke/package/package.json
- test/smoke/package/resources/ExpoSample/App.js
- test/smoke/package/src/debugIos.test.ts
- test/smoke/package/src/helpers/utilities.ts
- test/smoke/package/yarn.lock
Changes:
- Fix https://github.com/microsoft/vscode-react-native/issues/1198 - used functions from [react-native-community/cli](https://github.com/react-native-community/cli) repository:
- [getTargetBuildDir](https://github.com/react-native-community/cli/blob/master/packages/platform-ios/src/commands/runIOS/index.ts#L369-L374)
- [getBuildPath](https://github.com/react-native-community/cli/blob/master/packages/platform-ios/src/commands/runIOS/index.ts#L376-L414)
- Fix smoke tests for iOS and Expo.
> Fix getting of iOS build path according to React Native CLI v3.1.0 features

- src/extension/exponent/exponentPlatform.ts
This PR adds `expoHostType` property to `ExponentPlatform.runApp` telemetry event.
Example:
> Add telemetry for Expo host types

- package-lock.json
- package.json
- src/common/utils.ts
- src/debugger/rnDebugSession.ts
- src/extension/appLauncher.ts
- src/extension/commandPaletteHandler.ts
- src/extension/projectsStorage.ts
- src/extension/rn-extension.ts
- src/extension/rnDebugAdapterDescriptorFactory.ts
The list of changes:
* Refactored projects caching - created a separate class that intended to store projects data and provide access to them
* Implemented Debug Adapter Server within Debug Adapter Descriptor Factory approach
* Added new Debug Session class implementation intended to be used with [js-debug extension](https://github.com/microsoft/vscode-js-debug). So now js-debug attach scenario is called from our debug session where we make only some preparations for debugging.
> Refactoring of caching of projects instances

- src/cdp-proxy/reactNativeCDPProxy.ts
- src/common/utils.ts
- src/debugger/rnDebugSession.ts
- src/extension/log/LogHelper.ts
- src/extension/log/OutputChannelLogger.ts
- Now it's possible to add timestamp to a log message and use custom tags as well as log levels tags for logging, an output will look something like this:
```
[2020-03-03 22:08:01] [My Tag] message"
```
- Added port definition during attach event handling
> Fix port definition on attaching and enhance logging

- src/debugger/nodeDebugWrapper.ts
This error is only connected to incorrect handling of projectRoot parameter, but renders even if `react-native-tools.logLevel` is enabled and can be confusing.
#1230
> Enhance error message in case of error when projectRoot parameter is missing

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
Added a couple issue templates so users can report issues or new features more easily.
When clicking in "new issue" the should see a menu to choose the template similar to the following (this is from another repo):
Feel free to suggest any other fields or information that might be useful!
> feat: issue templates

- test/smoke/package/package.json
- test/smoke/package/yarn.lock
Updated versions in smoke tests dependencies for fixing vulnerability.
Updated dependencies:
- `axios` from version `0.19.0`  to `0.21.1`
- `expo/xdl` from version `59.0.14` to `59.0.17`
> Update versions in smoke tests dependencies

- package.json
- package.nls.json
- src/debugger/debugSessionBase.ts
- src/debugger/jsDebugConfigAdapter.ts
Now there is problem with processing time of 'createFromSourceMap' function of js-debug. So we disable `sourceMapRenames` option by default.
> Add support for sourceMapRenames config option

- src/common/packager.ts
- src/debugger/direct/directDebugSession.ts
#1720 
Add connection to packager and listen for message indicating that another debugger has connected.
Only works on iOS because of Hermes bug https://github.com/facebook/react-native/issues/32904
> Add WebSocket connection to packager & stop debugging when another debugger is connected

- src/extension/rn-extension.ts
Anyone trying to test the latest builds of react-native is unable to use this extension due to the version check.  Canary builds of react-native are published with a version `0.0.0-<date/commit tag>`
The extension should work with those versions.
> Allow extension to work on canary builds of RN

- src/cdp-proxy/reactNativeCDPProxy.ts
- src/common/packager.ts
- src/debugger/debugSessionBase.ts
- src/debugger/direct/directDebugSession.ts
- src/debugger/rnDebugSession.ts
https://github.com/microsoft/vscode-react-native/issues/1731
> Improve direct debug session termination

- src/common/telemetry.ts
- test/resources/processExecution/simulator.ts
> Fix deprecated new Buffer() to Buffer.from

- README.md
- test/smoke/package/yarn.lock
> [Feature] Update documentation for Expo SDK 48
